<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.3.6" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PetCare.Modules.IdentityAndPets\PetCare.Modules.IdentityAndPets.csproj" />
    <ProjectReference Include="..\PetCare.Modules.Booking\PetCare.Modules.Booking.csproj" />
    <ProjectReference Include="..\PetCare.Modules.Providers\PetCare.Modules.Providers.csproj" />
    <ProjectReference Include="..\PetCare.Modules.Billing\PetCare.Modules.Billing.csproj" />
    <ProjectReference Include="..\PetCare.IntegrationEvents\PetCare.IntegrationEvents.csproj" />
  </ItemGroup>

</Project>
